Update Node packages and reformat
MarkusJx/install-boost pull request #47
Opened 2024-10-09 11:10 UTC by permanentdaylightt

2024-10-11 16:02 UTC, MarkusJx commented
On which code style is your re-formatted code based on? By default this project uses prettier for formatting TypeScript code

2024-10-11 18:09 UTC, permanentdaylightt commented
well didnt knew that, i jst tried to compress up some things by hand

2024-10-11 19:10 UTC, MarkusJx commented
You shouldn't do that, it'll make branch merging basically impossible. You could run `npm run prettier:fix` to restore the old formatting or I'll just accept the package updates, those are long overdue

2024-10-13 07:50 UTC, permanentdaylightt commented
ok i may make another workflow just to format

2024-10-13 08:45 UTC, MarkusJx commented
Creating a workflow for formatting the code isn't really the way to go here, a workflow checking the code style would be far better. And yes, I didn't create such a workflow because I was lazy.

2024-10-13 12:22 UTC, permanentdaylightt commented
:p i will try to make one

2024-10-13 12:25 UTC, permanentdaylightt commented
can u look onto this?

2024-10-13 12:30 UTC, permanentdaylightt commented
OR WAIT LOL

2024-10-13 12:49 UTC, permanentdaylightt commented
okay its done but im unsure if its working? the files seem to be non formatted tho

2024-10-13 13:54 UTC, MarkusJx commented
That's because you can't write files persistently during a workflow run (well, you *technically can*, I wouldn't accept such a MR because that is just bad design and nobody should do that). You'll have to run `npm run prettier:fix` on you local machine and commit the result.

2024-10-13 13:58 UTC, MarkusJx requested changes
I've added some notes to your workflow, didn't look at any of the other changes, will do that once the formatting is fixed

2024-10-13 13:58 UTC, MarkusJx commented on .github/workflows/run-prettier.yml
> +          version: 9
```suggestion
```
Remove this, I'm not using pnpm (I know it's faster and I don't care)

2024-10-13 13:58 UTC, MarkusJx commented on .github/workflows/run-prettier.yml
> +        run: pnpm prettier . --write
```suggestion
        run: npm prettier . --check
```

2024-10-13 13:58 UTC, MarkusJx commented on .github/workflows/run-prettier.yml
> +        run: pnpm install -D
```suggestion
        run: npm ci
```

2024-10-13 13:58 UTC, MarkusJx commented on .github/workflows/run-prettier.yml
> +    runs-on: windows-latest
```suggestion
    runs-on: ubuntu-latest
```
Ubuntu is the way

2024-10-13 13:58 UTC, MarkusJx commented on .github/workflows/run-prettier.yml
> +  workflow_dispatch:
```suggestion
  push:
```

2024-10-13 13:58 UTC, MarkusJx commented on .github/workflows/run-prettier.yml
> +name: Run Prettier
```suggestion
name: Lint
```

2024-10-13 13:58 UTC, MarkusJx commented on .github/workflows/run-prettier.yml
> +  run-prettier:
```suggestion
  check-format:
```

2024-10-14 13:12 UTC, permanentdaylightt commented
well it still fails

2024-10-19 11:42 UTC, MarkusJx requested changes

2024-10-19 11:42 UTC, MarkusJx commented on .github/workflows/lint.yml
> +        run: npx prettier . --write
```suggestion
        run: npx prettier . --check
```
Please don't try to create a format workflow. Just run `npm run prettier:fix` locally and commit the result

2024-10-19 11:42 UTC, MarkusJx commented on LICENSE
> +Copyright (c) 2024 MarkusJx
```suggestion
Copyright (c) 2020 - 2024 MarkusJx
```

2024-10-19 12:46 UTC, permanentdaylightt commented
we still have to run --write after running check

2024-10-19 13:22 UTC, MarkusJx commented
> we still have to run --write after running check

No, we don't and we shouldn't. Formatting should be done by the developer locally and the formatted version must be pushed. The workflow *must not* format the code.

2024-10-20 16:41 UTC, permanentdaylightt commented
mb

2024-10-20 16:41 UTC, permanentdaylightt commented
so ur gonna format locally?

2024-10-20 16:46 UTC, MarkusJx commented
you should do it since you are the author of this pull request

2024-10-20 16:47 UTC, permanentdaylightt commented
lel

2025-01-06 11:53 UTC, MarkusJx commented
I've moved the lint workflow to #48 as I don't really see any benefit in keeping any of the other changes

2025-01-06 11:53 UTC, closed without merging